### ISSUE TITLE
Warning from Check

### ISSUE THREAD

**Issue by LiNk-NY** [LiNk-NY/SummarizedExperiment#1]
When running package check after building:  
```
Undocumented S4 methods:
  generic '[' and siglist 'Assays,ANY,ANY,ANY'
  generic '[' and siglist 'SummarizedExperiment,ANY,ANY,ANY'
```
@mtmorgan should this be of concern?

**Comment by mtmorgan** [comment]
The man page requires that all arguments be specified, but setMethod() defaults to ANY when the argument is not specified in the signature, so it's tempting to only document the methods that are actually defined, rather than the implicitly defined method. But this is closed with https://github.com/Bioconductor-mirror/SummarizedExperiment/commit/4bb757f012d613f6c3e04e60afbf04a804dcd85f Thanks!
